.PHONY: clean All

All:
	@echo "----------Building project:[ Tree - Debug ]----------"
	@cd "C:\Users\ADMIN\Desktop\DSA\Tree" && "$(MAKE)" -f  "Tree.mk"
clean:
	@echo "----------Cleaning project:[ Tree - Debug ]----------"
	@cd "C:\Users\ADMIN\Desktop\DSA\Tree" && "$(MAKE)" -f  "Tree.mk" clean
